# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A1QEQEvJRv0ibhj5hds9NaQCk1joz02x
"""

# Step 1: Install necessary libraries
!pip install streamlit pyngrok tensorflow opencv-python-headless numpy

# Step 2: Mount Google Drive to access the model file
from google.colab import drive
drive.mount('/content/drive')

# Step 3: Import Libraries
import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from pyngrok import ngrok

# Step 4: Load the Pre-trained Model
model_path = '/content/drive/MyDrive/model.keras'  # Update this path if needed
model = tf.keras.models.load_model(model_path)

# Step 5: Define Image Processing Functions
def convert_to_nir(image):
    nir_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    nir_image = np.stack((nir_image,) * 3, axis=-1)
    return nir_image

def preprocess_image(image):
    resized_image = cv2.resize(image, (256, 256))
    normalized_image = resized_image / 255.0
    return np.expand_dims(normalized_image, axis=0)

# Step 7: Set up the ngrok tunnel
ngrok.set_auth_token("2o4V6TzjTG3ov8Cl3SrK5268Jqe_6JSTERvi6kARpBVWtRXMX")  # Replace with your actual auth token
public_url = ngrok.connect("http://localhost:8501")  # Specify the protocol with 'http://localhost:8501'
print(f"Access your app here: {public_url}")

!pgrep ngrok | xargs kill -9

# Step 8: Run the Streamlit app
!streamlit run app.py &>/content/logs.txt &